{
 "title": "Kafka Parallel Computation Demo",
 "description": "Monitors the performance of the Kafka Scale parallel computer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Downloaded GZips",
   "type": "gauge",
   "description": "Displays the number of census gzips that have been downloaded and are in the process of being submitted for processing",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GZips" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "kafka_scale_downloaded_gzips", "legendFormat": "downloaded gzips" }
   ]
  },
  {
   "title": "Compute Queue Chunks Written",
   "type": "graph",
   "description": "Total chunks written to the compute queue",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_scale_chunks_written", "legendFormat": "chunks written" }
   ]
  },
  {
   "title": "Compute Queue Submission Rate",
   "type": "graph",
   "description": "The rate at which chunks are submitted to the compute queue by the reader pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_scale_chunks_written[5m])",
     "legendFormat": "chunk rate"
    }
   ]
  },
  {
   "title": "Compute Queue Processing Rate",
   "type": "graph",
   "description": "The rate of compute messages read by compute pods from the compute topics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_scale_compute_messages_read{pod=~\".*\"}[5m])",
     "legendFormat": "compute messages read"
    }
   ]
  },
  {
   "title": "Result Queue Processing Rate",
   "type": "graph",
   "description": "Compute messages read from the result queue by the accumulator pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_scale_result_messages_read[5m])",
     "legendFormat": "result message read"
    }
   ]
  }
 ]
}