apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-scale-results
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-scale-results
spec:
  replicas: 1
  selector:
    matchLabels:
      appzygy.net/name: results
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-scale-results
        appzygy.net/name: results
        appzygy.net/observable: "true"
    spec:
      containers:
      - name: reader
        image: quay.io/appzygy/kafka-scale:1.0.1
        imagePullPolicy: Always
        args:
        - --kafka=my-cluster-kafka-bootstrap:9092
        - --results-port=8888
        - --with-metrics
        - --metrics-port=9123
        - results
        ports:
        - name: metrics
          containerPort: 9123
        - name: results
          containerPort: 8888
        resources:
          requests:
            memory: "20Mi"
            cpu: "100m"
          limits:
            memory: "40Mi"
            cpu: "100m"
      serviceAccount: default
      serviceAccountName: default
