apiVersion: v1
kind: Service
metadata:
  name: kafka-scale-results
  namespace: kafka
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    appzygy.net/name: results
  type: NodePort
