apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-scale-read
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-scale-read
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-scale-read
        appzygy.net/name: read
        appzygy.net/observable: "true"
    spec:
      containers:
      - name: read
        image: quay.io/appzygy/kafka-scale:1.0.0
        imagePullPolicy: Always
        args:
        - --kafka=my-cluster-kafka-bootstrap:9092
        - --verbose
        - --years=2018,2019
        - --months=jan
        - --compute-topic-partitions=10
        - --compute-topic-replfactor=1
        - --chunks=1000
        - --with-metrics
        - --metrics-port=9123
        - read
        ports:
        - name: metrics
          containerPort: 9123
        resources:
          requests:
            memory: "20Mi"
            cpu: "300m"
          limits:
            memory: "40Mi"
            cpu: "300m"
      restartPolicy: Never
      serviceAccount: default
      serviceAccountName: default
  backoffLimit: 4